# Copy and paste from copy_file3.py starting here ..............................
screen.onkey(lambda: key_press_handler('a'), 'a')
screen.onkey(lambda: key_press_handler('b'), 'b')
screen.onkey(lambda: key_press_handler('c'), 'c')
screen.onkey(lambda: key_press_handler('d'), 'd')
screen.onkey(lambda: key_press_handler('e'), 'e')
screen.onkey(lambda: key_press_handler('f'), 'f')
screen.onkey(lambda: key_press_handler('g'), 'g')
screen.onkey(lambda: key_press_handler('h'), 'h')
screen.onkey(lambda: key_press_handler('i'), 'i')
screen.onkey(lambda: key_press_handler('j'), 'j')
screen.onkey(lambda: key_press_handler('k'), 'k')
screen.onkey(lambda: key_press_handler('l'), 'l')
screen.onkey(lambda: key_press_handler('m'), 'm')
screen.onkey(lambda: key_press_handler('n'), 'n')
screen.onkey(lambda: key_press_handler('o'), 'o')
screen.onkey(lambda: key_press_handler('p'), 'p')
screen.onkey(lambda: key_press_handler('q'), 'q')
screen.onkey(lambda: key_press_handler('r'), 'r')
screen.onkey(lambda: key_press_handler('s'), 's')
screen.onkey(lambda: key_press_handler('t'), 't')
screen.onkey(lambda: key_press_handler('u'), 'u')
screen.onkey(lambda: key_press_handler('v'), 'v')
screen.onkey(lambda: key_press_handler('w'), 'w')
screen.onkey(lambda: key_press_handler('x'), 'x')
screen.onkey(lambda: key_press_handler('y'), 'y')
screen.onkey(lambda: key_press_handler('z'), 'z')

screen.listen()
# Copy and paste from copy_file3.py ending here ................................